
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: WHEEL
    exclude_types: [json]
  - id: forbid-new-submodules
  - id: trailing-whitespace
    exclude: .patch
    exclude_types: [json]

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    files: \.(py|pyi)$
    args: [--line-length=100]

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.1
  hooks:
    - id: ruff
      args: ["--fix", "--show-fixes"]

# We use the Python version instead of the original version which seems to require Docker
# https://github.com/koalaman/shellcheck-precommit
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.8.0.4
  hooks:
    - id: shellcheck
      name: shellcheck
      args: ["--severity=warning"]

- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.14.1
  hooks:
    - id: check-jsonschema
      name: "Check GitHub Workflows"
      files: ^\.github/workflows/
      types: [yaml]
      args: ["--schemafile", "https://json.schemastore.org/github-workflow"]
