# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the doc/ directory with Sphinx
sphinx:
   configuration: doc/conf.py

# Set the version of Python and requirements required to build the docs.
python:
   version: 3.7
   install:
   - requirements: doc/docs-requirements.txt
